ASP.NET/csharp-web-master/csharp-web-master/2020-Sept-Season/MyFirstAspNetCoreApplication/MyFirstAspNetCoreApplication/Models/ErrorViewModel.cs
using System;

namespace MyFirstAspNetCoreApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.NET/csharp-web-master/csharp-web-master/2020-Sept-Season/MyFirstAspNetCoreApplication/MyFirstAspNetCoreApplication/ViewModels/Home/IndexViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MyFirstAspNetCoreApplication.ViewModels.Home
{
    public class IndexViewModel
    {
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Range(2000, 2100)]
        public int Year { get; set; }

        public int UsersCount { get; set; }

        public int Processors { get; set; }

        public int Id { get; set; }

        public string Name { get; set; }
    }
}

ASP.NET/csharp-web-master/csharp-web-master/2020-Sept-Season/MyFirstAspNetCoreApplication/MyFirstAspNetCoreApplication/ViewModels/ViewComponents/RegisteredUsersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstAspNetCoreApplication.ViewModels.ViewComponents
{
    public class RegisteredUsersViewModel
    {
        public string Title { get; set; }

        public int Users { get; set; }
    }
}

ASP.NET/csharp-web-master/csharp-web-master/2020-Sept-Season/MyFirstAspNetCoreApplication/MyFirstAspNetCoreApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MyFirstAspNetCoreApplication.Data;
using MyFirstAspNetCoreApplication.Filters;
using MyFirstAspNetCoreApplication.Models;
using MyFirstAspNetCoreApplication.Service;
using MyFirstAspNetCoreApplication.ViewModels.Home;

namespace MyFirstAspNetCoreApplication.Controllers
{
    [TypeFilter(typeof(AddHeaderActionFilterAttribute))]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext dbContext;
        private readonly IWebHostEnvironment hostingEnvironment;
        private readonly IConfiguration configuration;
        private readonly IInstanceCounter instanceCounter;

        public HomeController(
            ILogger<HomeController> logger,
            ApplicationDbContext dbContext,
            IWebHostEnvironment hostingEnvironment,
            IConfiguration configuration,
            IInstanceCounter instanceCounter)
        {
            _logger = logger;
            this.dbContext = dbContext;
            this.hostingEnvironment = hostingEnvironment;
            this.configuration = configuration;
            this.instanceCounter = instanceCounter;
        }

        [Authorize]
        public IActionResult Index(int id, int year, int month)
        {
            Debug.WriteLine(this.hostingEnvironment.EnvironmentName);
            var viewModel = new IndexViewModel
            {
                Id = id,
                Name = "Anonymous",
                Year = DateTime.UtcNow.Year,
                Processors = Environment.ProcessorCount,
                UsersCount = this.dbContext.Users.Count(),
                Description = "Курсът \"ASP.NET Core\" ще ви научи как се изграждат съвременни уеб приложения с архитектурата Model-View-Controller, използвайки HTML5, бази данни, Entity Framework Core и други технологии. Изучава се технологичната платформа ASP.NET Core, нейните компоненти и архитектура, създаването на MVC уеб приложения, дефинирането на модели, изгледи и частични изгледи с Razor view engine, дефиниране на контролери, работа с бази данни и интеграция с Entity Framework Core, LINQ и SQL Server. Курсът включа и по-сложни теми като работа с потребители, роли и сесии, използване на AJAX, кеширане, сигурност на уеб приложенията, уеб сокети и работа с библиотеки от MVC контроли.",
            };
            return this.View(viewModel);
        }

        public IActionResult Exception()
        {
            throw new Exception();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult ContactForm()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ContactForm(string title, string content)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            // TODO: Save title and content in DB...

            return this.RedirectToAction(nameof(Index));
        }

        public IActionResult StatusCodeError(int errorCode)
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET/csharp-web-master/csharp-web-master/2020-Sept-Season/MyFirstAspNetCoreApplication/MyFirstAspNetCoreApplication/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstAspNetCoreApplication.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyFirstAspNetCoreApplication.Controllers
{
    public class InfoController : Controller
    {
        public IActionResult Time()
        {
            return this.Content(DateTime.Now.ToLongTimeString());
        }

        public IActionResult Date()
        {
            return this.Content(DateTime.Now.ToLongDateString());
        }
    }
}

ASP.NET/csharp-web-master/csharp-web-master/2020-Sept-Season/MyFirstAspNetCoreApplication/MyFirstAspNetCoreApplication/ViewComponents/RegisteredUsersViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstAspNetCoreApplication.Data;
using MyFirstAspNetCoreApplication.Service;
using MyFirstAspNetCoreApplication.ViewModels.ViewComponents;
using System.Linq;

namespace MyFirstAspNetCoreApplication.ViewComponents
{
    public class RegisteredUsersViewComponent : ViewComponent
    {
        private readonly ApplicationDbContext dbContext;

        public RegisteredUsersViewComponent(
            ApplicationDbContext dbContext,
            IInstanceCounter instanceCounter)
        {
            this.dbContext = dbContext;
        }

        public IViewComponentResult Invoke(string title)
        {
            var users = this.dbContext.Users.Count();
            var viewModel = new RegisteredUsersViewModel
            {
                Title = title,
                Users = users,
            };
            
            return this.View(viewModel);
        }
    }
}

ASP.NET/csharp-web-master/csharp-web-master/2020-Sept-Season/MyFirstAspNetCoreApplication/MyFirstAspNetCoreApplication/Views/Home/ContactForm.cshtml
<form method="post">
    <input name="title" class="form-control" />
    <input name="content" class="form-control"  />
    <input type="submit" />
</form>

ASP.NET/csharp-web-master/csharp-web-master/2020-Sept-Season/MyFirstAspNetCoreApplication/MyFirstAspNetCoreApplication/Views/Home/Index.cshtml
@using System.Text
@model IndexViewModel
@inject IShortStringService ShortString
@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment WebEnvironment
@inject Microsoft.Extensions.Configuration.IConfiguration Configuration
@inject IInstanceCounter InstanceCounter
@{
    // Comment
    ViewData["Title"] = "Welcome Page";
}

<h1>Instances: @InstanceCounter.Instances</h1>
<h1>@WebEnvironment.EnvironmentName</h1>
<h2>@this.Configuration["HelloMessage"]</h2>
<vc:registered-users title="Registered users" />
<partial name="_HomePageStart" model="Model" />

<form asp-action="Index">
    <textarea asp-for="Description"class="form-control col-md-3" ></textarea>
    <input asp-for="Name" class="form-control col-md-3" />
    <input asp-for="Processors"class="form-control col-md-3"  />
</form>

<hr />

<div class="text-center">
    @if (User.Identity.IsAuthenticated)
    {
        // Comment
        <h1 class="display-4">Welcome, @User.Identity.Name</h1>
    }
    else
    {
        <h1 class="display-4">Welcome, @Model.Name</h1>
    }
    <h2>It @Model.Year year.</h2>
    <p>@ShortString.GetShort(Model.Description, 200)</p>
    <p>We have @Model.UsersCount users.</p>
    @* Comment *@
    <p>Processors: @Model.Processors</p>
    <p>Time: @DateTime.Now</p>
    <p>Id: @Model.Id</p>
</div>
<!-- HTML Comment -->


<table bootstrap-table="" table-name="Digits table">
    @for (int i = 0; i < 10; i++)
    {
        <tr><td>@i</td></tr>
    }
</table>

@section Links {
    <li class="nav-item">
        <a class="nav-link text-dark" href="https://google.com">Google</a>
    </li>
}

ASP.NET/csharp-web-master/csharp-web-master/2020-Sept-Season/MyFirstAspNetCoreApplication/MyFirstAspNetCoreApplication/Views/Home/StatusCodeError.cshtml
<h1>Error!</h1>
<img src="https://softuni.bg/Content/images/404animation.gif" />

ASP.NET/csharp-web-master/csharp-web-master/2020-Sept-Season/MyFirstAspNetCoreApplication/MyFirstAspNetCoreApplication/Views/Home/_HomePageStart.cshtml
@model IndexViewModel
<div class="alert alert alert-primary">
    @Model?.Description
</div>

ASP.NET/csharp-web-master/csharp-web-master/2020-Sept-Season/MyFirstAspNetCoreApplication/MyFirstAspNetCoreApplication/Views/Shared/Components/RegisteredUsers/Default.cshtml
@model MyFirstAspNetCoreApplication.ViewModels.ViewComponents.RegisteredUsersViewModel

<span class="text-danger font-weight-bold">@Model.Title: @Model.Users</span>